### ISSUE TITLE
geoip

### ISSUE THREAD

**Issue by Findarato** [molu8bits/squid-filebeat-kibana#1]
No matter what I do my location values are not a geo_point

**Comment by molu8bits** [comment]
Geoip requires a few elements:
- elasticsearch must have installed geoip module:
e.g.
sudo /usr/share/elasticsearch/bin/elasticsearch-plugin install ingest-geoip
- mapping must be created on the Elasticsearch index before sending any documents to it.
- IP address 

The location values require mapping which should be created *before* sending any logs to filebeat.
If any entries exist inside of filebeat it is not possible to change the mapping without recreating index. If default mapping is applied then values are wrong. if any other Filebeat sends logs to this EL first - it possibly creates default mapping for filebeat index and it will not be work with Squid Beat.
Thats why in troubleshooting I suggest removing filebeat index from current day + remove pipeline.

Have you tried this instruction? Be carefull as it removes documents from particular day index. Please stop all filebeat services before the action. Here are the steps

1. Do only once
cat filebeat/etc/squid-fields.yml >> /etc/filebeat/fields.yml 
2. Replace filebeat-index-name with the name of appropriate Elastichsearch index e.g. "filebeat-6.5.0-2019.04.30" or "filebeat-2019.04.30". This must match with datatime from Squid log files.
curl -XDELETE elasticsearch.local:9200/filebeat-index-name 
3. Remove ingest pipeline (Filebeat recreates it back when send first logs)
curl -XDELETE elasticsearch.local:9200/_ingest/pipeline/filebeat*squid*
4. Start again Filebeat service on the node.
systemctl restart filebeat

What version of elasticsearch have you tried ? Is it docker instance ?
