### ISSUE TITLE
Squid Native format - 10 fields supported

### ISSUE THREAD

**Issue by Randy-312** [molu8bits/squid-filebeat-kibana#2]
Should this also support the 10 native fields for the squid native access?
https://wiki.squid-cache.org/Features/LogFormat

Perhaps that would be squid.access.clf. and squid.access.native. for those instead.

**Comment by molu8bits** [comment]
Hmm, 
As long as I understand squid logformat options this filebeat works for native format.
I mean here that it should be appropriate when logformat "squid" is used for access_log inside squid.conf (or is not set at all as it should be a default option at least for Squid 3.5):
`#access_log /var/log/squid/access.log squid`

Native format then produces logs like below:

> 1567416819.945     89 192.168.0.1 TCP_HIT/200 1300 GET http://www.somedomain/file.tgz - HIER_NONE/- application/octet-stream



But if access_log directive is set to "common" inside squid.conf:

`access_log /var/log/squid/access.log common`

Then CLF is used and log line looks like below:

> 192.168.0.1 - - [07/Sep/2019:14:55:44 +0200] "GET http://www.somedomain/file.tgz HTTP/1.1" 200 87532 TCP_SWAPFAIL_MISS:ORIGINAL_DST

CLF will not work with this filebeat.

**Comment by Randy-312** [comment]
Thanks for confirming this is just Native format.
We're looking at the mapping of these fields for CLF.  We'll look at your Squid Native work to see if we can incorporate it into [ECS-549](https://github.com/elastic/ecs/issues/549)
@kiran545

**Comment by Randy-312** [comment]
Should this identify that it's Squid.Native format somehow then?

Also, we welcome your involvement in the ECS Mapping conversation.
