### ISSUE TITLE
Imported Failed Failed to import 7 of 7 objects. Import failed

### ISSUE THREAD

**Issue by JayStarrco** [molu8bits/squid-filebeat-kibana#3]
I have got to the point when you import 01_visualisations_All.json and I received this error. 
Import failed
Failed to import 7 of 7 objects. Import failed

Could not locate that index-pattern-field (id: squid.access.squid_request_status) Could not locate that index-pattern-field (id: squid.access.request_url) Could not locate that index-pattern-field (id: squid.access.dst_host) Could not locate that index-pattern-field (id: squid.access.src_ip) Could not locate that index-pattern-field (id: squid.access.http_status_code) Could not locate that index-pattern-field (id: squid.access.http_method) Could not locate that index-pattern-field (id: squid.access.dst_host)

Thanks for the help

**Comment by JayStarrco** [comment]
I restarted kibana nginx and elasticsearch. Once they came back up I was then able to import everything but the geoip. Which from what I read is no longer a plugin but a module. What do I need to do to get this work?

/# bash /usr/share/elasticsearch/bin/elasticsearch-plugin  install ingest-geoip
A tool for managing installed elasticsearch plugins

Commands
--------
list - Lists installed elasticsearch plugins
install - Install a plugin
remove - removes a plugin from Elasticsearch

Non-option arguments:
command

Option         Description
------         -----------
-h, --help     show help
-s, --silent   show minimal output
-v, --verbose  show verbose output
ERROR: Unknown plugin ingest-geoip


The geoip processor is no longer distributed as a plugin, but is now a module distributed by default with Elasticsearch

https://www.elastic.co/guide/en/elasticsearch/plugins/master/ingest-geoip.html

**Comment by molu8bits** [comment]
Yes, install ingest-geoip is not needed any longer since elasticsearch 6.7. Will update README with this information. Thanks.

**Comment by JayStarrco** [comment]
There is still an issue with visualizations for the geoip. How do we get that to work with the geoip module?
Could not locate that visualization (id: Squid_DST)

**Comment by molu8bits** [comment]
This visualisation should be imported together with the other ones. It might be that for some reason it failed. Or the id is different. You can check if inside Kibana visualisation you can find any visualisation named "SQUID_DST" and then if it works. If it doesn't exist then try to import attached one below. 

[SQUID_DST_export.zip](https://github.com/molu8bits/squid-filebeat-kibana/files/3637438/SQUID_DST_export.zip)

Let me know the results.

**Comment by JayStarrco** [comment]
I checked and there was no visualization named "SQUID_DST". I then tried to
import the NDJSON file you provided but it showed an error message
Sorry, there was an error

The file could not be processed.


Thank you for your help

**Comment by molu8bits** [comment]
The dashboards, visualisation and query come from the older version of Kibana. I think this could be a problem or the order in instruction is not correct. But all of them have been imported on my Kibana 7.3 without any warning or error. Probably I would need to test the procedure on some fresh elastic/kibana installation. Anyway creating that visualisation is quite easy when the rest works. You can try to manually create missing visualisation SQUID_DST by following instruction available now on wiki:
https://github.com/molu8bits/squid-filebeat-kibana/wiki

**Comment by tsmori** [comment]
Thanks for all the work on this. I'm stuck on step 5 of the manual SQUID_DST visualization. I'm still a little mystified by how the filebeat template is being created. It doesn't seem to pull everything in. I can see this field in the file, but the index only has the lat and long fields.

squid.access.geoip.location.lat
squid.access.geoip.location.lon

**Comment by molu8bits** [comment]
Two elements are crucial for for getting geoip visualisations.
At first mapping must be created _before_ creating an index

In my newest configuration the file /etc/squid/fields.yml is responsible for that:
`
 key: squid
  title: "squid"
  description: >
    squid Module
  fields:
    - name: squid
      type: group
      description: >
      fields:
...
          - name: geoip
            type: group
            fields:
              - name: continent_name
                type: alias
                path: squid.access.geoip.continent_name
                migration: true
              - name: country_iso_code
                type: alias
                path: squid.access.geoip.country_iso_code
                migration: true
              - name: location
                type: geo_point
                path: squid.access.geoip.location
                migration: true
              - name: region_name
                type: alias
                path: squid.access.geoip.region_name
                migration: true
              - name: city_name
                type: alias
                path: squid.access.geoip.city_name
                migration: true
              - name: region_iso_code
                type: alias
                path: squid.access.geoip.region_iso_code
                migration: true
`
To enforce creating a mapping from this field following three lines in /etc/filebeat/filebeat.yml are needed:
`
setup.template.fields: /etc/filebeat/fields.yml
setup.template.json.enabled: false
setup.template.overwrite: true
`

To check what mapping is set currently you can use e.g. following request from "Dev Tools"
`GET /filebeat-7.3.2-2019.09.14-000001/_mapping`

Somewhere in the response should be:
`
        "squid" : {
          "properties" : {
            "access" : {
              "properties" : {
                "content_type" : {
                  "type" : "keyword",
                  "ignore_above" : 1024
                },
                "dst_host" : {
                  "type" : "keyword",
                  "ignore_above" : 1024
                },
                "dst_ip" : {
                  "type" : "keyword",
                  "ignore_above" : 1024
                },
                "error" : {
                  "properties" : {
                    "message" : {
                      "type" : "keyword",
                      "ignore_above" : 1024
                    }
                  }
                },
                "geoip" : {
                  "properties" : {
                    "city_name" : {
                      "type" : "keyword",
                      "ignore_above" : 1024
                    },
                    "continent_name" : {
                      "type" : "keyword",
                      "ignore_above" : 1024
                    },
                    "country_iso_code" : {
                      "type" : "keyword",
                      "ignore_above" : 1024
                    },
                    "location" : {
                      "type" : "geo_point"
                    },
                    "region_iso_code" : {
                      "type" : "keyword",
                      "ignore_above" : 1024
                    },
                    "region_name" : {
                      "type" : "keyword",
                      "ignore_above" : 1024
                    }
                  }
                },
`
The crucial field is "location" with type "geo_point".

If that is missing that probably default mapping was used (elasticsearch didn't use modified fields.yml). To correct all filebeats writing to elasticsearch must be stopped, then the mapping of existing filebeat indexes must be removed and also deleted template for that filebeat . If its is cleaned then correct mapping should be created after starting again filebeat (with those three lines inside filebeat.yml configuration).

**Comment by tsmori** [comment]
Thanks for the info. Ultimately, I created a new index for squid data, once I found the new ILM settings. But the weird thing is that when I restarted filebeat using the new squid-filebeat index, the squid.access.geoip.location field was now in the index. I did scale the template down, pulling out a lot of defaults, but I didn't change any of the squid lines, so I'm not sure what I changed to make it start working.

**Comment by molu8bits** [comment]
Last time i started working on another filebeat module and had some trouble to have required mapping when old templates from filebeat 6.x still existsted. I needed to remove everything (templates), restarted  then they started working. Generally its always good to test the module on clean filebeat/elasticsearch. Of course Kibana index patterns must be refreshed as well.
