### ISSUE TITLE
config question

### ISSUE THREAD

**Issue by kdy1968** [molu8bits/squid-filebeat-kibana#5]
being abit of a noob...the following steps are abit confusing:

in this step we configure filebit.yml.....
c.) configure /etc/filebeat/filebeat.yml - reference file placed in /etc/filebeat/filebeat.yml (change hosts ["elasticsearch.local"] in section output.elastichsearch to elastichsarch instance listening from filebeat host

in this step..it says to replace the file we configred....thinking this is a typo....
e.) Replace /etc/filebeat/filebeat.yml with filebeat/etc/fields.yml from repo. (Before run filebeat - Critical !). This file is a compiled version from 7.3 so the rest of functionality will work.

**Comment by molu8bits** [comment]
Yeah, seems the typo.
Should be as follow:

> e.) Replace /etc/filebeat/fields.yml with filebeat/etc/fields.yml from repo. (Before run filebeat - Critical !). This file is a compiled version from 7.3 so the rest of functionality will work.

**Comment by molu8bits** [comment]
corrected
