### ISSUE TITLE
Any Plan to make a PR to elastic/beats?

### ISSUE THREAD

**Issue by herrBez** [molu8bits/squid-filebeat-kibana#6]
Hi there,

I used the module in a test environment, and I think it is well-done. Are you planning to open a PR to elastic/beats?

Kind regards,
Mirko

**Comment by molu8bits** [comment]
Hi, yes I am, 
I need to correct a few things first, I hope I'll find a couple of hours to do it during next few weeks.

**Comment by molu8bits** [comment]
https://github.com/elastic/beats/pull/19859
